{
 "title": "Maël Gangloff",
 "time": { "from": "2020-09-01T06:00:00.000Z", "to": "now" },
 "panels": [
  {
   "title": "Nombre total de notes",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT timestamp AS \"time\", COUNT(*) FROM devoirs"
    }
   ]
  },
  {
   "title": "Notes",
   "type": "graph",
   "gridPos": { "h": 18, "w": 21, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Note" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  matiere AS metric,\n  note\nFROM devoirs\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "J- Vacances",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  jMoins\nFROM holidays"
    }
   ]
  },
  {
   "title": "Moyennes générales",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 3, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  NOW() AS \"time\",\n  trimestre AS metric,\n  moyenneGenerale\nFROM moyenneGenerale\nORDER BY id"
    }
   ]
  },
  {
   "title": "Moyennes T1",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  idPeriode AS \"time\",\n  matiereLibelle AS metric,\n  moyenneEleve\nFROM moyennes\nWHERE\n  idPeriode = 25\nORDER BY idPeriode"
    }
   ]
  },
  {
   "title": "Moyennes T2",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  idPeriode AS \"time\",\n  matiereLibelle AS metric,\n  moyenneEleve\nFROM moyennes\nWHERE\n  idPeriode = 26\nORDER BY idPeriode"
    }
   ]
  },
  {
   "title": "Moyennes T3",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 28 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  idPeriode AS \"time\",\n  matiereLibelle AS metric,\n  moyenneEleve\nFROM moyennes\nWHERE\n  idPeriode = 27\nORDER BY idPeriode"
    }
   ]
  }
 ]
}